## data


In [73]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix, classification_report
import warnings
warnings.filterwarnings("ignore")

In [74]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [75]:
# read data
df1 = pd.read_csv("/content/drive/MyDrive/PROPOSAL dan TA/code/hadis_preprocessed_stemakhir.csv")
df2 = pd.read_csv("/content/drive/MyDrive/PROPOSAL dan TA/code/hadis_preprocessed_stemdulu.csv")

In [76]:
df1.head()

no_stopword  \
0  ['iman', 'memiliki', 'enam', 'puluh', 'cabang'...   
1  ['muslim', 'orang', 'kaum', 'muslimin', 'selam...   
2      ['makan', 'salam', 'orang', 'kenal', 'kenal']   
3  ['beriman', 'dicintainya', 'orang', 'tuanya', ...   
4  ['tanda', 'iman', 'mencintai', 'kaum', 'anshar...   

                                              bersih  Class  
0             iman milik enam puluh cabang malu iman      1  
1  muslim orang kaum muslimin selamat lisan tanga...      2  
2                      makan salam orang kenal kenal      1  
3                          iman cinta orang tua anak      1  
4  tanda iman cinta kaum anshar tanda nifaq benci...      1

In [77]:
df2.head()

no_stopword  \
0  ['iman', 'milik', 'enam', 'puluh', 'cabang', '...   
1  ['orang', 'muslim', 'orang', 'kaum', 'muslimin...   
2      ['makan', 'salam', 'orang', 'kenal', 'kenal']   
3  ['iman', 'orang', 'cinta', 'orang', 'tua', 'an...   
4  ['tanda', 'iman', 'cinta', 'kaum', 'anshar', '...   

                                              bersih  Class  
0             iman milik enam puluh cabang malu iman      1  
1  orang muslim orang kaum muslimin selamat lisan...      2  
2                      makan salam orang kenal kenal      1  
3                    iman orang cinta orang tua anak      1  
4  tanda iman cinta kaum anshar tanda nifaq benci...      1

##FE

In [78]:
# tf-idf 
tfidf_vect_ = TfidfVectorizer()
df_stemakhir_tfidf = tfidf_vect_.fit_transform(df1['bersih'].apply(lambda x:np.str_(x)))
df_stemakhir_tfidf.shape

(1626, 3429)

In [79]:
# tf-idf 
tfidf_vect_ = TfidfVectorizer()
df_stemdulu_tfidf = tfidf_vect_.fit_transform(df2['bersih'].apply(lambda x:np.str_(x)))
df_stemdulu_tfidf.shape

(1626, 3304)

## FS

In [80]:
def chi_square_stemakhir(x, y):
  chi2_selector_stemakhir = SelectKBest(chi2, k=280)
  X_kbest = chi2_selector_stemakhir.fit_transform(x, y)
  return X_kbest

In [81]:
def chi_square_stemdulu(x, y):
  chi2_selector_stemdulu = SelectKBest(chi2, k=280)
  X_kbest = chi2_selector_stemdulu.fit_transform(x, y)
  return X_kbest

In [82]:
y_stemakhir = df1['Class']
y_stemdulu = df2['Class']
x_stemakhir = chi_square_stemakhir(df_stemakhir_tfidf,y_stemakhir)
x_stemdulu = chi_square_stemdulu(df_stemdulu_tfidf,y_stemdulu)

In [83]:
print(x_stemakhir)

  (1, 157)	0.15384010234095807
  (1, 48)	0.11808167093311853
  (1, 86)	0.2231281227802018
  (1, 40)	0.12063390414165369
  (1, 1)	0.355474424547419
  (1, 2)	0.19429010273058223
  (1, 8)	0.07579194803039403
  (1, 128)	0.08520954700454651
  (2, 114)	0.8930142647656351
  (2, 137)	0.2514675578471607
  (5, 8)	0.23864026891433107
  (7, 114)	0.8930142647656351
  (7, 137)	0.2514675578471607
  (8, 23)	0.2486119867562923
  (9, 181)	0.3301846182119189
  (9, 23)	0.28853219279732195
  (10, 8)	0.24068428045348086
  (11, 60)	0.32114867240049016
  (11, 125)	0.5462871667060112
  (13, 117)	0.4236138774863708
  (13, 157)	0.11052592991140121
  (14, 259)	0.47101884786088777
  (15, 73)	0.16556072520070717
  (15, 75)	0.17551306433860733
  (17, 111)	0.18200013420074893
  :	:
  (1617, 236)	0.2525239326432366
  (1617, 5)	0.13868401381869572
  (1617, 157)	0.11699145081503505
  (1617, 40)	0.18347797808577612
  (1617, 8)	0.1152756638255668
  (1618, 197)	0.4285878812993604
  (1618, 59)	0.4549068941738173
  (1619, 8)

In [84]:
print(x_stemdulu)

  (1, 156)	0.15131355493419033
  (1, 47)	0.11614239154534448
  (1, 84)	0.21946364406880678
  (1, 40)	0.11865270890686465
  (1, 2)	0.34963639550397746
  (1, 3)	0.19109923670966242
  (1, 10)	0.07454720139517884
  (1, 127)	0.0838101332188026
  (1, 163)	0.24051518738528696
  (2, 112)	0.9001165898295072
  (2, 137)	0.2534675307583631
  (2, 163)	0.161095967834975
  (3, 257)	0.5059333652367984
  (3, 163)	0.4023000177288325
  (5, 10)	0.23864026891433107
  (7, 112)	0.9001165898295072
  (7, 137)	0.2534675307583631
  (7, 163)	0.161095967834975
  (8, 24)	0.2486119867562923
  (9, 182)	0.3301846182119189
  (9, 24)	0.28853219279732195
  (10, 10)	0.23518270110908623
  (11, 58)	0.32114867240049016
  (11, 124)	0.5462871667060112
  (12, 163)	0.14896317063026612
  :	:
  (1617, 7)	0.14482355889957382
  (1617, 156)	0.12217066553905692
  (1617, 40)	0.19160055318861852
  (1617, 10)	0.12037892061268617
  (1618, 199)	0.4311708698432222
  (1618, 57)	0.45764850061544693
  (1618, 257)	0.35254919134298973
  (1618, 1

In [85]:
print("Untuk Stem Akhir")
print('Original feature number:', df_stemakhir_tfidf.shape[1])
print('Reduced feature number:', x_stemakhir.shape[1])

Untuk Stem Akhir
Original feature number: 3429
Reduced feature number: 280


In [86]:
print("Untuk Stem Dahulu")
print('Original feature number:', df_stemdulu_tfidf.shape[1])
print('Reduced feature number:', x_stemdulu.shape[1])

Untuk Stem Dahulu
Original feature number: 3304
Reduced feature number: 280


In [87]:
# membagi train test data (stemakhir)

X_train_stemakhir, X_test_stemakhir, y_train_stemakhir, y_test_stemakhir = train_test_split(x_stemakhir, y_stemakhir, test_size=0.2, random_state=0)

print("X Train : ", (X_train_stemakhir.shape))
print("y Train : ", (y_train_stemakhir.shape))
print("X Test : ", (X_test_stemakhir.shape))
print("y Test : ", (y_test_stemakhir.shape))

X Train :  (1300, 280)
y Train :  (1300,)
X Test :  (326, 280)
y Test :  (326,)


In [88]:
# membagi train test data (stemdulu)

X_train_stemdulu, X_test_stemdulu, y_train_stemdulu, y_test_stemdulu = train_test_split(x_stemdulu, y_stemdulu, test_size=0.2, random_state=0)

print("X Train : ", (X_train_stemdulu.shape))
print("y Train : ", (y_train_stemdulu.shape))
print("X Test : ", (X_test_stemdulu.shape))
print("y Test : ", (y_test_stemdulu.shape))

X Train :  (1300, 280)
y Train :  (1300,)
X Test :  (326, 280)
y Test :  (326,)


## Modeling

In [89]:
# stem akhir

xg = XGBClassifier()

xg.fit(X_train_stemakhir, y_train_stemakhir)
predictions_stemakhir = xg.predict(X_test_stemakhir)
print(accuracy_score(y_test_stemakhir, predictions_stemakhir))
print(confusion_matrix(y_test_stemakhir, predictions_stemakhir))
print(classification_report(y_test_stemakhir, predictions_stemakhir))

0.6993865030674846
[[89  1  8]
 [22 74 12]
 [46  9 65]]
              precision    recall  f1-score   support

           1       0.57      0.91      0.70        98
           2       0.88      0.69      0.77       108
           3       0.76      0.54      0.63       120

    accuracy                           0.70       326
   macro avg       0.74      0.71      0.70       326
weighted avg       0.74      0.70      0.70       326



In [90]:
# stem dulu

xg = XGBClassifier()

xg.fit(X_train_stemdulu, y_train_stemdulu)
predictions_stemdulu = xg.predict(X_test_stemdulu)
print(accuracy_score(y_test_stemdulu, predictions_stemdulu))
print(confusion_matrix(y_test_stemdulu, predictions_stemdulu))
print(classification_report(y_test_stemdulu, predictions_stemdulu))

0.7239263803680982
[[90  1  7]
 [24 74 10]
 [40  8 72]]
              precision    recall  f1-score   support

           1       0.58      0.92      0.71        98
           2       0.89      0.69      0.77       108
           3       0.81      0.60      0.69       120

    accuracy                           0.72       326
   macro avg       0.76      0.73      0.73       326
weighted avg       0.77      0.72      0.73       326

